"""Glue between tungtungarmor and PyInstaller.

The strategy is deliberately simple and robust: obfuscate the project into
a working directory (including the self-contained runtime package), then run
PyInstaller against the *obfuscated* entry script.  Because the obfuscated
files and the runtime are ordinary importable Python, PyInstaller bundles
them like any other source -- no C extension or custom bootloader needed.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from typing import List, Optional

from .packer import DEFAULT_RUNTIME_PKG, ObfuscateOptions, pack

SPEC_TEMPLATE = '''\
# -*- mode: python ; coding: utf-8 -*-
# Generated by tungtungarmor for an already-obfuscated project.
block_cipher = None

a = Analysis(
    [{entry!r}],
    pathex=[{pathex!r}],
    binaries=[],
    datas=[],
    hiddenimports=[{hiddenimports}],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    cipher=block_cipher,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name={name!r},
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console={console},
    onefile={onefile},
)
'''


def generate_spec(
    entry: Path,
    pathex: Path,
    name: str,
    *,
    runtime_pkg: str = DEFAULT_RUNTIME_PKG,
    console: bool = True,
    onefile: bool = True,
    out: Optional[Path] = None,
) -> Path:
    spec = SPEC_TEMPLATE.format(
        entry=str(entry),
        pathex=str(pathex),
        hiddenimports=repr(runtime_pkg),
        name=name,
        console=console,
        onefile=onefile,
    )
    out = out or Path(f"{name}.spec")
    out.write_text(spec, encoding="utf-8")
    return out


def _pyinstaller_available() -> bool:
    try:
        import PyInstaller  # noqa: F401
        return True
    except Exception:
        return False


def build(
    entry: Path,
    *,
    project_root: Optional[Path] = None,
    work_dir: Path = Path("build/tungtungarmor_obf"),
    dist_dir: Path = Path("dist"),
    name: Optional[str] = None,
    onefile: bool = True,
    console: bool = True,
    options: Optional[ObfuscateOptions] = None,
    extra_args: Optional[List[str]] = None,
) -> int:
    """Obfuscate *entry* (and its project) then build it with PyInstaller.

    Returns the PyInstaller process exit code.
    """
    if not _pyinstaller_available():
        raise RuntimeError(
            "PyInstaller is not installed. Install it with:\n"
            "    pip install pyinstaller"
        )

    entry = Path(entry).resolve()
    project_root = Path(project_root).resolve() if project_root else entry.parent
    options = options or ObfuscateOptions()
    name = name or entry.stem
    work_dir = Path(work_dir).resolve()

    # 1. Obfuscate the whole project tree into the work dir.
    result = pack(project_root, work_dir, options)

    # 2. Locate the obfuscated entry inside the work dir.
    rel_entry = entry.relative_to(project_root)
    obf_entry = work_dir / rel_entry
    if not obf_entry.exists():
        raise RuntimeError(f"obfuscated entry not found: {obf_entry}")

    # 3. Drive PyInstaller against the obfuscated entry.
    cmd = [
        sys.executable, "-m", "PyInstaller",
        str(obf_entry),
        "--name", name,
        "--paths", str(work_dir),
        "--hidden-import", options.runtime_pkg,
        "--collect-submodules", options.runtime_pkg,
        "--distpath", str(Path(dist_dir).resolve()),
        "--workpath", str(work_dir / "_pyi_work"),
        "--specpath", str(work_dir),
        "--noconfirm",
    ]
    cmd.append("--onefile" if onefile else "--onedir")
    cmd.append("--console" if console else "--windowed")
    if extra_args:
        cmd.extend(extra_args)

    print("tungtungarmor: running", " ".join(cmd))
    proc = subprocess.run(cmd)
    return proc.returncode
