"""Glue between tungtungarmor and PyInstaller.

The strategy is deliberately simple and robust: obfuscate the project into
a working directory (including the self-contained runtime package), then run
PyInstaller against the *obfuscated* entry script.  Because the obfuscated
files and the runtime are ordinary importable Python, PyInstaller bundles
them like any other source -- no C extension or custom bootloader needed.
"""

from __future__ import annotations

import os
import shlex
import subprocess
import sys
from pathlib import Path
from typing import Iterable, List, Optional

from .packer import DEFAULT_RUNTIME_PKG, ObfuscateOptions, pack


def _has_flag(tokens: Iterable[str], names: Iterable[str]) -> bool:
    """True if any flag in *names* (or its ``--flag=value`` form) is present."""
    names = tuple(names)
    for tok in tokens:
        if tok in names:
            return True
        if any(tok.startswith(n + "=") for n in names):
            return True
    return False

SPEC_TEMPLATE = '''\
# -*- mode: python ; coding: utf-8 -*-
# Generated by tungtungarmor for an already-obfuscated project.
block_cipher = None

a = Analysis(
    [{entry!r}],
    pathex=[{pathex!r}],
    binaries=[],
    datas=[],
    hiddenimports=[{hiddenimports}],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    cipher=block_cipher,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name={name!r},
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console={console},
    onefile={onefile},
)
'''


def generate_spec(
    entry: Path,
    pathex: Path,
    name: str,
    *,
    runtime_pkg: str = DEFAULT_RUNTIME_PKG,
    console: bool = True,
    onefile: bool = True,
    out: Optional[Path] = None,
) -> Path:
    spec = SPEC_TEMPLATE.format(
        entry=str(entry),
        pathex=str(pathex),
        hiddenimports=repr(runtime_pkg),
        name=name,
        console=console,
        onefile=onefile,
    )
    out = out or Path(f"{name}.spec")
    out.write_text(spec, encoding="utf-8")
    return out


def _pyinstaller_available() -> bool:
    try:
        import PyInstaller  # noqa: F401
        return True
    except Exception:
        return False


def build(
    entry: Path,
    *,
    project_root: Optional[Path] = None,
    work_dir: Path = Path("build/tungtungarmor_obf"),
    dist_dir: Path = Path("dist"),
    name: Optional[str] = None,
    onefile: bool = True,
    console: bool = True,
    options: Optional[ObfuscateOptions] = None,
    protection=None,
    exclude: Optional[List[str]] = None,
    follow_imports: bool = False,
    include: Optional[List[str]] = None,
    pyi_options: Optional[str] = None,
    extra_args: Optional[List[str]] = None,
) -> int:
    """Obfuscate *entry* (and its project) then build it with PyInstaller.

    Extra PyInstaller flags can be supplied two ways (both forwarded verbatim):

    * *pyi_options* -- a single string, PyArmor-``pyi_options`` style, e.g.
      ``"-w -i app.ico --name 'My App' --add-data assets;assets"``. It is split
      with :func:`shlex.split`.
    * *extra_args*  -- an already-tokenised list of flags.

    Flags you provide there take precedence: tungtungarmor only injects its own
    ``--name`` / ``--onefile|--onedir`` / ``--console|--windowed`` defaults when
    you did *not* specify them yourself, so nothing is passed twice.

    Returns the PyInstaller process exit code.
    """
    if not _pyinstaller_available():
        raise RuntimeError(
            "PyInstaller is not installed. Install it with:\n"
            "    pip install pyinstaller"
        )

    entry = Path(entry).resolve()
    project_root = Path(project_root).resolve() if project_root else entry.parent
    options = options or ObfuscateOptions()
    name = name or entry.stem
    work_dir = Path(work_dir).resolve()

    # Collect user-supplied PyInstaller flags from both sources.
    extra: List[str] = []
    if pyi_options:
        extra.extend(shlex.split(pyi_options, posix=(os.name != "nt")))
    if extra_args:
        extra.extend(extra_args)

    # 1. Obfuscate the project into the work dir.
    if follow_imports:
        from .scanner import discover
        files, modules = discover(
            entry, project_root, include,
            on_warn=lambda m: print("tungtungarmor: warn:", m),
        )
        print(f"tungtungarmor: scanned imports from {entry.name} -> "
              f"{len(files)} project file(s)")
        result = pack(project_root, work_dir, options,
                      protection=protection, only_files=sorted(files))
        # Auto-add discovered local modules as hidden imports so PyInstaller
        # bundles them (their real imports are hidden inside encrypted blobs).
        entry_module = None
        try:
            entry_module = entry.relative_to(project_root).with_suffix("").as_posix().replace("/", ".")
        except ValueError:
            pass
        auto_hidden: List[str] = []
        for mod in sorted(modules):
            if mod and mod != entry_module:
                auto_hidden += ["--hidden-import", mod]
        extra = auto_hidden + extra
    else:
        result = pack(project_root, work_dir, options,
                      protection=protection, exclude=exclude)

    # 2. Locate the obfuscated entry inside the work dir.
    rel_entry = entry.relative_to(project_root)
    obf_entry = work_dir / rel_entry
    if not obf_entry.exists():
        raise RuntimeError(f"obfuscated entry not found: {obf_entry}")

    # 3. Drive PyInstaller against the obfuscated entry.
    cmd = [
        sys.executable, "-m", "PyInstaller",
        str(obf_entry),
        "--paths", str(work_dir),
        "--hidden-import", options.runtime_pkg,
        "--collect-submodules", options.runtime_pkg,
        "--distpath", str(Path(dist_dir).resolve()),
        "--workpath", str(work_dir / "_pyi_work"),
        # Spec lives in the project root so relative --add-data / -i paths
        # (e.g. "assets;assets") resolve against the project, not the obf dir.
        "--specpath", str(project_root),
        "--noconfirm",
    ]
    # Only inject defaults the user hasn't overridden, to avoid duplicate flags.
    if not _has_flag(extra, ("--name", "-n")):
        cmd += ["--name", name]
    if not _has_flag(extra, ("--onefile", "-F", "--onedir", "-D")):
        cmd.append("--onefile" if onefile else "--onedir")
    if not _has_flag(extra, ("--console", "-c", "--nowindowed",
                             "--windowed", "-w", "--noconsole")):
        cmd.append("--console" if console else "--windowed")
    cmd.extend(extra)

    print("tungtungarmor: running", " ".join(shlex.quote(c) for c in cmd))
    proc = subprocess.run(cmd)
    return proc.returncode
